name: Test
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:12.10-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0
      - name: Install
        run: yarn
      - name: Test
        run: yarn test
        env:
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
